### ISSUE TITLE
Add a distribution builder package

### ISSUE THREAD

**Issue by bergos** [rdf-ext/discussions#11]
The distribution builder should use browserify to create browser distributions. It should include a command line and web interface.

It's already work in progress...

**Comment by retog** [comment]
I think to make adoption easy its more convenient to have different distributions available via cdn, at  least a very comprehensive one (rdf-ext-full.js) and a reasonably modular one where one manually adds the required features (rdf-ext.js, xy-parser.js, xy-backend.js). These should be created and deployed by travis.

**Comment by bergos** [comment]
Good point, having a full package and maybe some other bundles was also the idea. The CLI version can be build these packages automatically. But I don't like the idea of having the parsers/packages separate. At the end it will be only confusing for the user. x doesn't work without y or x and y contain many redundant packages.

**Comment by bergos** [comment]
There is now a [rdf-ext-dist-builder repository](https://github.com/rdf-ext/rdf-ext-dist-builder). Issues/discussions should be handled in that repo.
