### ISSUE TITLE
Why also have callback functions if we promises?

### ISSUE THREAD

**Issue by retog** [rdf-ext/discussions#17]
I think having to pass null arguments as in 

```
N3Parser.parse($("#data").text(), null, window.location.toString()).then(
```

is quite ugly. Wouldn't it be good to get rid of those as soon as possible?

**Comment by bergos** [comment]
I agree. The callback API is only there for better backwards compatibility. RDF-Ext 1.0.0 will be based on the output of the [Representation Task Force](https://github.com/rdfjs/rdfjs.org/wiki/Representation-Task-Force). I will propose to use only Promises and Streams.
