### ISSUE TITLE
Create package for mime type utils

### ISSUE THREAD

**Issue by bergos** [rdf-ext/discussions#7]
The [mime type utils](https://github.com/rdf-ext/rdf-ext/blob/master/lib/utils.js#L166) are only usefull when many parsers and serializers are registered. To remove the dependencies from the rdf-ext package, the code should get it's own package. Any proposals for a package name?

**Comment by retog** [comment]
A bit a suggestive title, what package name do you suggest for my foobar utils? ;)

see https://github.com/rdf-ext/rdf-mime-type-util/issues/1

**Comment by bergos** [comment]
@retog @nicola 
I would like to move the ParserUtil and SerializerUtil class to the rdf-ext package. How would you name it? Just plural Parsers and Serializers? Should the class name contain media type? Any suggestions?

**Comment by nicola** [comment]
I think I want a package for like this one. I would prefer to not require two packages

**Comment by bergos** [comment]
@nicola We should keep this one. Maybe we rename it to rdf-common-formats or something like that in version 1.x. I just like to move the classes which manage the parsers and serialiers to the core lib. You still need to register the parsers and serialiers and the mime-type-utils package will still provide the same features. But that would allow to use the mime type handling with a reduce set of parsers and serialiers.

**Comment by retog** [comment]
"Parsers and Serializers" if fine for me. As for the package that depends on all "known" parsers and serialize I think `rdf-common-formats` is good.

**Comment by nicola** [comment]
`rdf-formats` :+1:

**Comment by retog** [comment]
It's just **common** formats, `rdf-formats` seems misleading to me as it might be interpreted as to bee supporting all concrete syntaxes or worse to be required for using any concrete syntax.

**Comment by bergos** [comment]
I renamed the package to `rdf-formats-common`. I think that pattern is nicer, because we could have packages like `rdf-formats-html` in the future.

**Comment by retog** [comment]
Great Name! (I was afraid you would name it after a space fog :) )

**Comment by bergos** [comment]
@retog 

```
{
  "name": "rdf-blue-marble",
  "description": "RDF formats of planet earth"
}
```

:smile:

But @nicola brought up a [good point](https://github.com/nicola/folder-to-rdf/pull/2). I expect there will be a rc5...

**Comment by retog** [comment]
+1 :)
