### ISSUE TITLE
Use Git flow?

### ISSUE THREAD

**Issue by retog** [rdf-ext/discussions#8]
http://nvie.com/posts/a-successful-git-branching-model/
https://de.atlassian.com/git/tutorials/comparing-workflows/centralized-workflow

**Comment by bergos** [comment]
+1

**Comment by bergos** [comment]
[CONTRIBUTING.md](https://github.com/rdf-ext/rdf-ext/blob/master/CONTRIBUTING.md#branches) contains a section about branches and Git flow.
